-- MySQL Script generated by MySQL Workbench
-- Mon Apr  9 12:07:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TAB_PESSOA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_PESSOA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_PESSOA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(80) NULL,
  `TELEFONE` VARCHAR(20) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_VENDEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_VENDEDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_VENDEDOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MATRICULA` INT NOT NULL,
  `DATA_ADM` DATE NULL,
  `SALARIO` DOUBLE NULL,
  `PESSOA` INT NOT NULL,
  PRIMARY KEY (`ID`, `PESSOA`),
  INDEX `fk_Vendedor_Pessoa_idx` (`PESSOA` ASC),
  CONSTRAINT `fk_Vendedor_Pessoa`
    FOREIGN KEY (`PESSOA`)
    REFERENCES `mydb`.`TAB_PESSOA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENDERECO` VARCHAR(200) NULL,
  `PESSOA` INT NOT NULL,
  PRIMARY KEY (`ID`, `PESSOA`),
  INDEX `fk_Cliente_Pessoa1_idx` (`PESSOA` ASC),
  CONSTRAINT `fk_Cliente_Pessoa1`
    FOREIGN KEY (`PESSOA`)
    REFERENCES `mydb`.`TAB_PESSOA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_VENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_VENDA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_VENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` INT NOT NULL,
  `DATA_VENDA` DATE NULL,
  `VALOR` DOUBLE NULL,
  `VENDEDOR` INT NOT NULL,
  `CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID`, `VENDEDOR`, `CLIENTE`),
  INDEX `fk_Venda_Vendedor1_idx` (`VENDEDOR` ASC),
  INDEX `fk_Venda_Cliente1_idx` (`CLIENTE` ASC),
  CONSTRAINT `fk_Venda_Vendedor1`
    FOREIGN KEY (`VENDEDOR`)
    REFERENCES `mydb`.`TAB_VENDEDOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`CLIENTE`)
    REFERENCES `mydb`.`TAB_CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_PRODUTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_PRODUTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `VALOR` DOUBLE NULL,
  `ESTOQUE` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_ITEM_VENDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_ITEM_VENDA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_ITEM_VENDA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUANTIDADE` INT NULL,
  `VALOR` DOUBLE NULL,
  `VENDA` INT NOT NULL,
  `PRODUTO` INT NOT NULL,
  PRIMARY KEY (`ID`, `VENDA`, `PRODUTO`),
  INDEX `fk_ItemVenda_Venda1_idx` (`VENDA` ASC),
  INDEX `fk_ItemVenda_Produto1_idx` (`PRODUTO` ASC),
  CONSTRAINT `fk_ItemVenda_Venda1`
    FOREIGN KEY (`VENDA`)
    REFERENCES `mydb`.`TAB_VENDA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemVenda_Produto1`
    FOREIGN KEY (`PRODUTO`)
    REFERENCES `mydb`.`TAB_PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_FORNECEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_FORNECEDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_FORNECEDOR` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` VARCHAR(200) NULL,
  `CNPJ` VARCHAR(20) NULL,
  `TELEFONE` VARCHAR(20) NULL,
  `ENDERECO` VARCHAR(200) NULL,
  `CODIGO` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_COMPRA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_COMPRA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` INT NOT NULL,
  `DATA_COMPRA` DATETIME NULL,
  `VALOR` DOUBLE NULL,
  `FORNECEDOR` INT NOT NULL,
  PRIMARY KEY (`ID`, `FORNECEDOR`),
  INDEX `fk_TAB_COMPRA_TAB_FORNECEDOR1_idx` (`FORNECEDOR` ASC),
  CONSTRAINT `fk_TAB_COMPRA_TAB_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR`)
    REFERENCES `mydb`.`TAB_FORNECEDOR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TAB_ITEM_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TAB_ITEM_COMPRA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TAB_ITEM_COMPRA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QUANTIDADE` INT NULL,
  `VALOR` DOUBLE NULL,
  `PRODUTO` INT NOT NULL,
  `COMPRA` INT NOT NULL,
  PRIMARY KEY (`ID`, `PRODUTO`, `COMPRA`),
  INDEX `fk_TAB_ITEM_COMPRA_TAB_PRODUTO1_idx` (`PRODUTO` ASC),
  INDEX `fk_TAB_ITEM_COMPRA_TAB_COMPRA1_idx` (`COMPRA` ASC),
  CONSTRAINT `fk_TAB_ITEM_COMPRA_TAB_PRODUTO1`
    FOREIGN KEY (`PRODUTO`)
    REFERENCES `mydb`.`TAB_PRODUTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAB_ITEM_COMPRA_TAB_COMPRA1`
    FOREIGN KEY (`COMPRA`)
    REFERENCES `mydb`.`TAB_COMPRA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
